const storageKey="asq-reference-qfd-v1";
const projectDefaults={projectName:"",productService:"",owner:"",customerSegment:"",revision:"A",reviewDate:new Date().toISOString().slice(0,10)};
const demo={project:{...projectDefaults,projectName:"Example: Customer Portal Redesign",productService:"Digital self-service portal",owner:"Product & Quality Team",customerSegment:"Existing customers"},needs:[{name:"Easy to learn",importance:5,current:3,target:5},{name:"Fast to complete",importance:5,current:2,target:5},{name:"Reliable results",importance:4,current:3,target:5},{name:"Easy to share",importance:3,current:2,target:4}],responses:[{name:"Onboarding time",direction:"down",target:"≤ 5 min"},{name:"Steps per task",direction:"down",target:"≤ 8"},{name:"Validation coverage",direction:"up",target:"≥ 95%"},{name:"Export formats",direction:"up",target:"≥ 3"}],relations:[[9,3,1,0],[1,9,3,1],[3,1,9,1],[0,1,3,9]]};
let state=loadState();
const ids=Object.keys(projectDefaults);const head=document.querySelector("#matrixHead"),body=document.querySelector("#matrixBody"),foot=document.querySelector("#matrixFoot"),saveState=document.querySelector("#saveState");
for(const id of ids){const el=document.querySelector(`#${id}`);el.value=state.project[id]||"";el.addEventListener("input",()=>{state.project[id]=el.value;persist()})}
document.querySelector("#addNeed").onclick=addNeed;document.querySelector("#addNeedBottom").onclick=addNeed;document.querySelector("#addResponse").onclick=addResponse;document.querySelector("#addResponseBottom").onclick=addResponse;document.querySelector("#loadDemo").onclick=()=>{state=structuredClone(demo);syncProject();render();persist()};document.querySelector("#clearAll").onclick=()=>{state={project:{...projectDefaults},needs:[],responses:[],relations:[]};syncProject();render();persist()};document.querySelector("#exportJson").onclick=exportJson;document.querySelector("#exportCsv").onclick=exportCsv;document.querySelector("#importJson").onchange=importJson;
render();
function loadState(){try{const saved=JSON.parse(localStorage.getItem(storageKey));if(saved&&Array.isArray(saved.needs)&&Array.isArray(saved.responses))return saved}catch{}return structuredClone(demo)}
function syncProject(){for(const id of ids)document.querySelector(`#${id}`).value=state.project[id]||""}
function persist(){localStorage.setItem(storageKey,JSON.stringify(state));saveState.textContent="Saved locally";clearTimeout(persist.timer);persist.timer=setTimeout(()=>saveState.textContent="Autosave ready",1200)}
function options(selected){return [1,2,3,4,5].map(v=>`<option${v===Number(selected)?" selected":""}>${v}</option>`).join("")}
function render(){renderHead();renderBody();renderFoot();renderAnalysis();updateSummary()}
function renderHead(){head.innerHTML="";const tr=document.createElement("tr");tr.innerHTML='<th class="corner">Voice of the Customer</th><th class="rating-head">Importance</th><th class="rating-head">Current</th><th class="rating-head">Target</th>';state.responses.forEach((r,i)=>{const th=document.createElement("th");th.className="technical-head";th.innerHTML=`<button class="delete-control" title="Delete technical response">×</button><textarea aria-label="Technical response">${escapeHtml(r.name)}</textarea><select aria-label="Direction"><option value="up"${r.direction==="up"?" selected":""}>↑ Maximize</option><option value="down"${r.direction==="down"?" selected":""}>↓ Minimize</option><option value="target"${r.direction==="target"?" selected":""}>◎ Target</option></select>`;th.querySelector("button").onclick=()=>removeResponse(i);th.querySelector("textarea").oninput=e=>{r.name=e.target.value;persist();renderAnalysis();updateSummary()};th.querySelector("select").oninput=e=>{r.direction=e.target.value;persist()};tr.appendChild(th)});head.appendChild(tr)}
function renderBody(){body.innerHTML="";state.needs.forEach((need,rowIndex)=>{const tr=document.createElement("tr");tr.innerHTML=`<th class="need-cell"><button class="delete-control" title="Delete customer need">×</button><textarea aria-label="Customer need">${escapeHtml(need.name)}</textarea></th><td class="rating"><select>${options(need.importance)}</select></td><td class="rating"><select>${options(need.current)}</select></td><td class="rating"><select>${options(need.target)}</select></td>`;tr.querySelector("button").onclick=()=>removeNeed(rowIndex);tr.querySelector("textarea").oninput=e=>{need.name=e.target.value;persist();renderAnalysis()};const selects=tr.querySelectorAll("select");["importance","current","target"].forEach((field,i)=>selects[i].oninput=e=>{need[field]=Number(e.target.value);persist();renderFoot();renderAnalysis();updateSummary()});state.responses.forEach((_,colIndex)=>{const td=document.createElement("td");const value=state.relations[rowIndex]?.[colIndex]||0;td.innerHTML=`<button class="relation-button rel-${value}" aria-label="Relationship strength ${value}">${value||"—"}</button>`;td.querySelector("button").onclick=()=>cycleRelation(rowIndex,colIndex);tr.appendChild(td)});body.appendChild(tr)})}
function renderFoot(){foot.innerHTML="";const scores=getScores(),max=Math.max(...scores,1);const target=document.createElement("tr");target.className="target-row";target.innerHTML='<th>Technical Target</th><td colspan="3"></td>';state.responses.forEach((r,i)=>{const td=document.createElement("td");td.innerHTML=`<input value="${escapeAttr(r.target)}" aria-label="Technical target" />`;td.querySelector("input").oninput=e=>{state.responses[i].target=e.target.value;persist();renderAnalysis()};target.appendChild(td)});foot.appendChild(target);const score=document.createElement("tr");score.className="score-row";score.innerHTML='<th>Weighted Priority</th><td colspan="3"></td>';scores.forEach(v=>{const td=document.createElement("td");td.innerHTML=`<strong>${v}</strong><span class="score-bar"><i style="width:${v/max*100}%"></i></span>`;score.appendChild(td)});foot.appendChild(score)}
function getScores(){return state.responses.map((_,c)=>state.needs.reduce((sum,n,r)=>sum+n.importance*(state.relations[r]?.[c]||0),0))}
function cycleRelation(r,c){const values=[0,1,3,9],current=state.relations[r][c];state.relations[r][c]=values[(values.indexOf(current)+1)%values.length];renderBody();renderFoot();renderAnalysis();persist()}
function addNeed(){state.needs.push({name:"New customer need",importance:3,current:3,target:5});state.relations.push(state.responses.map(()=>0));render();persist()}
function removeNeed(i){state.needs.splice(i,1);state.relations.splice(i,1);render();persist()}
function addResponse(){state.responses.push({name:"New technical response",direction:"up",target:"TBD"});state.relations.forEach(row=>row.push(0));render();persist()}
function removeResponse(i){state.responses.splice(i,1);state.relations.forEach(row=>row.splice(i,1));render();persist()}
function updateSummary(){document.querySelector("#needCount").textContent=state.needs.length;document.querySelector("#responseCount").textContent=state.responses.length;const scores=getScores(),top=scores.length?scores.indexOf(Math.max(...scores)):-1;document.querySelector("#topPriority").textContent=top>=0?(state.responses[top].name||"Unnamed"):"—"}
function renderAnalysis(){const scores=getScores(),max=Math.max(...scores,1),ranked=state.responses.map((r,i)=>({...r,score:scores[i]})).sort((a,b)=>b.score-a.score);document.querySelector("#priorityRanking").innerHTML=ranked.map((r,i)=>`<div class="rank-row"><span class="rank-number">${i+1}</span><span class="rank-copy"><strong>${escapeHtml(r.name)}</strong><small>${r.direction==="up"?"Maximize":r.direction==="down"?"Minimize":"Target"} · ${escapeHtml(r.target)}</small><span class="score-bar"><i style="width:${r.score/max*100}%"></i></span></span><span class="rank-score">${r.score}</span></div>`).join("")||"<p>No technical responses yet.</p>";const gaps=state.needs.map(n=>({...n,gap:n.target-n.current})).sort((a,b)=>b.gap-a.gap);document.querySelector("#gapRanking").innerHTML=gaps.map((n,i)=>`<div class="rank-row"><span class="rank-number">${i+1}</span><span class="rank-copy"><strong>${escapeHtml(n.name)}</strong><small>Current ${n.current} → Target ${n.target}</small></span><span class="rank-score ${n.gap>=2?"gap-high":""}">+${n.gap}</span></div>`).join("")||"<p>No customer needs yet.</p>"}
function exportJson(){download(JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2),"qfd-project.json","application/json")}
function exportCsv(){const headers=["Project","Product / Service","Customer Need","Importance","Current Satisfaction","Target Satisfaction",...state.responses.map(r=>r.name)];const rows=state.needs.map((n,i)=>[state.project.projectName,state.project.productService,n.name,n.importance,n.current,n.target,...state.relations[i]]);rows.push(["Weighted Priority","","","","","",...getScores()]);download([headers,...rows].map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),"qfd-house-of-quality.csv","text/csv")}
function importJson(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!Array.isArray(imported.needs)||!Array.isArray(imported.responses)||!Array.isArray(imported.relations))throw new Error();state={project:{...projectDefaults,...imported.project},needs:imported.needs,responses:imported.responses,relations:imported.relations};syncProject();render();persist()}catch{alert("That file could not be imported. Choose a JSON file exported from this application.")}event.target.value=""};reader.readAsText(file)}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function escapeHtml(value){return String(value??"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}
function escapeAttr(value){return escapeHtml(value).replace(/"/g,"&quot;")}
